
useHelm3: true
allowNamespaceDiscovery: true
ingress:
  enabled: true
  certManager: true
  hostname:
  tls: true
  annotations:
    ingress.kubernetes.io/force-ssl-redirect: "true"
    ingress.kubernetes.io/proxy-body-size: "0"
    kubernetes.io/ingress.class: "contour"
    cert-manager.io/cluster-issuer: "letsencrypt-contour-cluster-issuer"
    kubernetes.io/tls-acme: "true"

# Auth Proxy for OIDC support
# ref: https://github.com/kubeapps/kubeapps/blob/master/docs/user/using-an-OIDC-provider.md
authProxy:
   enabled: true
   provider: oidc
   clientSecret: FOO_SECRET
   cookieSecret: bm90LWdvb2Qtc2VjcmV0Cg==
   #oauthLoginURI: /oauth2/start
   #oauthLogoutURI: /oauth2/sign_out
   additionalFlags:

# Pinniped Support
# https://github.com/kubeapps/kubeapps/blob/master/docs/user/using-an-OIDC-provider-with-pinniped.md
pinnipedProxy:
  enabled: true

clusters:
 - name: default
   pinnipedConfig:
    enable: true

apprepository:
  initialRepos:
    - name: tac-repo
      url: https://charts.trials.tac.bitnami.com/demo
