useHelm3: true
allowNamespaceDiscovery: true
ingress:
  enabled: true
  certManager: true
  hostname:
  tls: true
  annotations:
    ingress.kubernetes.io/force-ssl-redirect: "true"
    ingress.kubernetes.io/proxy-body-size: "0"
    kubernetes.io/ingress.class: "contour"
    cert-manager.io/cluster-issuer: "letsencrypt-contour-cluster-issuer"
    kubernetes.io/tls-acme: "true"

# Auth Proxy for OIDC support
# ref: https://github.com/kubeapps/kubeapps/blob/master/docs/user/using-an-OIDC-provider.md
authProxy:
   enabled: true
   provider: oidc
   cookieSecret: bm90LWdvb2Qtc2VjcmV0Cg==
   additionalFlags:

# Pinniped Support
# https://liveandletlearn.net/post/kubeapps-on-tanzu-kubernetes-grid-13-part-2/
pinnipedProxy:
  enabled: true
  defaultAuthenticatorName: kubeapps-jwt-authenticator
  image:
    repository: bitnami/kubeapps-pinniped-proxy
    # Explicitly request the version of pinniped-proxy which supports the pre 0.6.0 version of pinniped.
    tag: 2.2.1-debian-10-r22 # TODO: Remove this when TKG bumps pinniped to 0.6.0+

clusters:
  - name: default
    pinnipedConfig:
      enable: true

apprepository:
  initialRepos:
    - name: tac-repo
      url: https://charts.trials.tac.bitnami.com/demo
