#@ load("@ytt:overlay", "overlay")
#@ load("@ytt:template", "template")
#@ load("@ytt:data", "data")
#@ load("@ytt:yaml", "yaml")


apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  labels:
    app: app-accelerator
  name: app-accelerator-httpproxy
  namespace: accelerator-system
spec:
  routes:
  - conditions:
    - prefix: /
    services:
    - name: acc-ui-server
      port: 80
  virtualhost:
    fqdn: #@ data.values["app-accelerator"].fqdn
    tls:
      secretName: app-accelerator-tls