#@ load("@ytt:overlay", "overlay")
#@ load("@ytt:template", "template")
#@ load("@ytt:data", "data")
#@ load("@ytt:yaml", "yaml")

apiVersion: cert-manager.io/v1beta1
kind: Certificate
metadata:
  annotations:
  name: app-accelerator-cert
  namespace: accelerator-system
spec:
  commonName: #@ data.values["app-accelerator"].fqdn
  dnsNames:
  - #@ data.values["app-accelerator"].fqdn
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-contour-cluster-issuer
  secretName: app-accelerator-tls