#@ load("@ytt:overlay", "overlay")
#@ load("@ytt:template", "template")
#@ load("@ytt:data", "data")
#@ load("@ytt:yaml", "yaml")


apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  labels:
    app: argocd
  name: argocd-httpproxy
  namespace: argocd
spec:
  routes:
  - conditions:
    - prefix: /
    services:
    - name: argocd-server
      port: 80
  virtualhost:
    fqdn: #@ data.values["argocd"].fqdn
    tls:
      secretName: argocd-tls