AWS_REGION: us-east-2
AWS_SSH_KEY_NAME: # Added by scripts
CLUSTER_NAME: # Added by scripts
OIDC_IDENTITY_PROVIDER_CLIENT_ID: # Added by scripts
OIDC_IDENTITY_PROVIDER_CLIENT_SECRET: # Added by scripts
OIDC_IDENTITY_PROVIDER_ISSUER_URL: # Added by scripts

# AWS_NODE_AZ: us-east-2a
INFRASTRUCTURE_PROVIDER: aws
CONTROL_PLANE_MACHINE_TYPE: c6g.xlarge # t3.large
NODE_MACHINE_TYPE: c6g.xlarge # t3.xlarge
AWS_VPC_CIDR: 10.0.0.0/16
AWS_PRIVATE_NODE_CIDR: 10.0.1.0/24
AWS_PUBLIC_NODE_CIDR: 10.0.0.0/24
ENABLE_CEIP_PARTICIPATION: "false"
CLUSTER_PLAN: dev
CLUSTER_CIDR: 100.96.0.0/11
SERVICE_CIDR: 100.64.0.0/13
BASTION_HOST_ENABLED: "true"
IDENTITY_MANAGEMENT_TYPE: oidc
MACHINE_HEALTH_CHECK_ENABLED: "true"
OIDC_IDENTITY_PROVIDER_GROUPS_CLAIM: groups
OIDC_IDENTITY_PROVIDER_NAME: ""
OIDC_IDENTITY_PROVIDER_SCOPES: openid,profile,email,groups,offline_access
OIDC_IDENTITY_PROVIDER_USERNAME_CLAIM: email
TKG_HTTP_PROXY_ENABLED: "false"
