AZURE_CLIENT_ID:
AZURE_CLIENT_SECRET: 
AZURE_CONTROL_PLANE_MACHINE_TYPE: 
AZURE_CONTROL_PLANE_SUBNET_CIDR: 10.0.0.0/16
AZURE_CONTROL_PLANE_SUBNET_NAME: 
AZURE_LOCATION: 
AZURE_NODE_MACHINE_TYPE: 
AZURE_NODE_SUBNET_CIDR: 10.1.0.0/16
AZURE_NODE_SUBNET_NAME: 
#AZURE_RESOURCE_GROUP: 
AZURE_SSH_PUBLIC_KEY_B64: 
AZURE_SUBSCRIPTION_ID: 
AZURE_TENANT_ID:
AZURE_VNET_CIDR: 
AZURE_VNET_NAME: 
#AZURE_VNET_RESOURCE_GROUP: 
CLUSTER_CIDR: 100.96.0.0/11
CLUSTER_NAME: 
SERVICE_CIDR: 100.64.0.0/13

# Defaults
IDENTITY_MANAGEMENT_TYPE: oidc
OIDC_IDENTITY_PROVIDER_GROUPS_CLAIM: groups
OIDC_IDENTITY_PROVIDER_NAME: "okta"
OIDC_IDENTITY_PROVIDER_SCOPES: openid,profile,email,groups,offline_access
OIDC_IDENTITY_PROVIDER_USERNAME_CLAIM: email
INFRASTRUCTURE_PROVIDER: azure
CLUSTER_PLAN: dev
TKG_HTTP_PROXY_ENABLED: "false"
ENABLE_CEIP_PARTICIPATION: "false"
ENABLE_MHC: "true"
