AZURE_SSH_PUBLIC_KEY_B64: 
AZURE_CLIENT_ID: 
AZURE_CLIENT_SECRET: 
AZURE_LOCATION: 
AZURE_SUBSCRIPTION_ID: 
AZURE_TENANT_ID: 

CLUSTER_PLAN: dev
ENABLE_AUDIT_LOGGING: true
ENABLE_DEFAULT_STORAGE_CLASS: true
