fullName:
  managementClusterName: ""
  name: ""
  provisionerName: ""
meta:
  labels: null
spec:
  clusterGroupName: ""
  tkgVsphere:
    distribution:
      version: "" # v1.20.5+vmware.2-tkg.1
      workspace:
        datacenter: "" # /Datacenter
        datastore: "" # /Datacenter/datastore/Bruce-2b
        folder: "" # /Datacenter/vm
        network: "" # /Datacenter/network/Bruce-20
        resourcePool: "" # /Datacenter/host/Bruce Cluster/Resources
    settings:
      network:
        controlPlaneEndpoint: "" # 10.20.30.199
        pods:
          cidrBlocks:
          - 172.20.0.0/16
        services:
          cidrBlocks:
          - 10.96.0.0/16
      security:
        sshKey: |
          ""
    topology:
      controlPlane:
        vmConfig:
          cpu: "2"
          diskGib: "20"
          memoryMib: "4096"
      nodePools:
      - info:
          description: default description for the nodepool
          name: default-node-pool
        spec:
          tkgVsphere:
            vmConfig:
              cpu: "2"
              diskGib: "20"
              memoryMib: "4096"
          workerNodeCount: "1"          
type:
  kind: Cluster
  package: vmware.tanzu.manage.v1alpha1.cluster
  version: v1alpha1