# To be changed by scripts based on params.yaml
CLUSTER_NAME: rito
VSPHERE_CONTROL_PLANE_ENDPOINT: 192.168.14.185
VSPHERE_SERVER: vcenter7.hyrulelab.com
VSPHERE_USERNAME: administrator@vsphere.local
VSPHERE_PASSWORD: "changeme"
VSPHERE_DATASTORE: /Datacenter/datastore/datastore
VSPHERE_FOLDER: /Datacenter/vm/tkg
VSPHERE_DATACENTER: /Datacenter
VSPHERE_NETWORK: TKG-VLAN14-PG
VSPHERE_RESOURCE_POOL: /Datacenter/host/Cluster/Resources/tkg
VSPHERE_SSH_AUTHORIZED_KEY: changeme
VSPHERE_TLS_THUMBPRINT: changeme

# Defaults
INFRASTRUCTURE_PROVIDER: vsphere
CLUSTER_PLAN: dev
SERVICE_CIDR: 100.64.0.0/13
TKG_HTTP_PROXY_ENABLED: "false"
ENABLE_CEIP_PARTICIPATION: "false"
ENABLE_MHC: "true"
CLUSTER_CIDR: 100.96.0.0/11
VSPHERE_CONTROL_PLANE_DISK_GIB: "40"
VSPHERE_CONTROL_PLANE_MEM_MIB: "4096"
VSPHERE_CONTROL_PLANE_NUM_CPUS: "2"
VSPHERE_WORKER_DISK_GIB: "40"
VSPHERE_WORKER_MEM_MIB: "4096"
VSPHERE_WORKER_NUM_CPUS: "2"
