# To be changed by scripts based on params.yaml
AVI_CA_DATA: #"changeme"
AVI_CLOUD_NAME: #Default-Cloud
AVI_CONTROLLER: #192.168.14.190
AVI_DATA_NETWORK: #VIP-VLAN15-PG
AVI_DATA_NETWORK_CIDR: #192.168.15.0/24
AVI_ENABLE: #"true"
AVI_LABELS: #""
AVI_PASSWORD: #"changeme"
AVI_SERVICE_ENGINE_GROUP: #Default-Group
AVI_USERNAME: #admin
CLUSTER_NAME: #gerudo
VSPHERE_CONTROL_PLANE_ENDPOINT: #192.168.14.185
VSPHERE_SERVER: #vcenter7.hyrulelab.com
VSPHERE_USERNAME: #administrator@vsphere.local
VSPHERE_PASSWORD: #"changeme"
VSPHERE_DATASTORE: #/Datacenter/datastore/datastore
VSPHERE_FOLDER: #/Datacenter/vm/tkg
VSPHERE_DATACENTER: #/Datacenter
VSPHERE_NETWORK: #TKG-VLAN14-PG
VSPHERE_RESOURCE_POOL: #/Datacenter/host/Cluster/Resources/tkg
VSPHERE_SSH_AUTHORIZED_KEY: #changeme
VSPHERE_TLS_THUMBPRINT: #changeme
OIDC_IDENTITY_PROVIDER_CLIENT_ID: #changeme
OIDC_IDENTITY_PROVIDER_CLIENT_SECRET: #changeme
OIDC_IDENTITY_PROVIDER_ISSUER_URL: #https://dev-281476.okta.com

# Defaults
IDENTITY_MANAGEMENT_TYPE: oidc
OIDC_IDENTITY_PROVIDER_GROUPS_CLAIM: groups
OIDC_IDENTITY_PROVIDER_NAME: "okta"
OIDC_IDENTITY_PROVIDER_SCOPES: openid,profile,email,groups,offline_access
OIDC_IDENTITY_PROVIDER_USERNAME_CLAIM: email
INFRASTRUCTURE_PROVIDER: vsphere
CLUSTER_PLAN: dev
SERVICE_CIDR: 100.64.0.0/13
TKG_HTTP_PROXY_ENABLED: "false"
ENABLE_CEIP_PARTICIPATION: "false"
ENABLE_MHC: "true"
CLUSTER_CIDR: 100.96.0.0/11
VSPHERE_CONTROL_PLANE_DISK_GIB: "40"
VSPHERE_CONTROL_PLANE_MEM_MIB: "4096"
VSPHERE_CONTROL_PLANE_NUM_CPUS: "2"
VSPHERE_WORKER_DISK_GIB: "40"
VSPHERE_WORKER_MEM_MIB: "4096"
VSPHERE_WORKER_NUM_CPUS: "2"
DEPLOY_TKG_ON_VSPHERE7: true
ENABLE_TKGS_ON_VSPHERE7: false
