# To be changed by scripts based on params.yaml
CLUSTER_NAME: # rito
VSPHERE_CONTROL_PLANE_ENDPOINT: # 192.168.14.185
VSPHERE_DATASTORE: #/Datacenter/datastore/datastore
VSPHERE_FOLDER: #/Datacenter/vm/tkg
VSPHERE_DATACENTER: #/Datacenter
VSPHERE_RESOURCE_POOL: #/Datacenter/host/Cluster/Resources/tkg
VSPHERE_SSH_AUTHORIZED_KEY: #changeme
VSPHERE_TLS_THUMBPRINT: #changeme
VSPHERE_NETWORK: #changeme

# Defaults
INFRASTRUCTURE_PROVIDER: vsphere
CLUSTER_PLAN: dev
ENABLE_MHC: "true"
VSPHERE_CONTROL_PLANE_DISK_GIB: "40"
VSPHERE_CONTROL_PLANE_MEM_MIB: "4096"
VSPHERE_CONTROL_PLANE_NUM_CPUS: "3"
VSPHERE_WORKER_DISK_GIB: "40"
VSPHERE_WORKER_MEM_MIB: "4096"
VSPHERE_WORKER_NUM_CPUS: "3"
