ingress:
  enabled: true

  annotations: 
    cert-manager.io/cluster-issuer: letsencrypt-contour-cluster-issuer
    ingress.kubernetes.io/force-ssl-redirect: "true"
    kubernetes.io/ingress.class: contour
    kubernetes.io/tls-acme: "true"

  hosts:
    - host: # Dyanamically Populated
      paths:
        - path: /
          pathType: ImplementationSpecific

  tls:
    - secretName: dex-cert
      hosts:
        - # Dyanamically Populated

config:
  issuer: # Dyanamically Populated
  expiry:
    signingKeys: 360m
    idTokens: 180m
  logger:
    level: info
    format: json
  staticClients:
    - redirectURIs:
        - # Dyanamically Populated
      id: kubeapps
      name: kubeapps
      secret: FOO_SECRET
  connectors:
    - type: oidc
      id: oidc
      name: oidc
      config:
        issuer: # Dyanamically Populated
        clientID: # Dyanamically Populated
        clientSecret: # Dyanamically Populated
        redirectURI: # Dyanamically Populated
        scopes:
          - openid
          - profile
          - email
          - groups
          - offline_access
        insecureEnableGroups: true
        getUserInfo: true
        userNameKey: email
        claimMapping:
          email: ""
          email_verified: email_verified
          groups: groups
          preferred_username: ""
        insecureSkipVerify: false
  oauth2:
    skipApprovalScreen: true
    responseTypes:
      - code
  storage:
    type: kubernetes
    config:
      inCluster: true
  enablePasswordDB: false
